In [3]:
import sys
import torch
import tqdm
import numpy as np
import random
import os
import json
sys.path.append('../')
from models.cnn.search_cnn import  SearchCNN, SearchCNNController
from configobj import ConfigObj

In [11]:
basecfg_path = '../configs/mnist/darts.cfg'  #конфиг, на который мы ориентируемся при загрузки модели
cfg = ConfigObj(basecfg_path)
name = cfg['name'] # имя для сохранения результатов
ckp_path = './var_nas/searchs/'+name+'/best_{}.pth.tar' # это шаблон названия сохраненных моделей
seeds = cfg['seeds'].split(';')  # сиды. можно брать из конфига
cfg['device'] = 'cpu'
sc = SearchCNNController(**cfg)

In [12]:
def calc_entropy(model, temp, entropy_sample_num = 100):
    entropy = 0
    for alpha in model.alpha_reduce:
        for subalpha in alpha:
            distr = torch.distributions.RelaxedOneHotCategorical(torch.ones(1)*temp, logits=subalpha)
            subentropy = 0
            for _ in range(entropy_sample_num):
                subentropy-=distr.log_prob(distr.sample())
            subentropy /= entropy_sample_num
            entropy += subentropy
    return entropy

In [14]:
# посмотрим, какова будет энтропия у моделей с низкой температурой и концентрацией плотности у одной из операций
# здесь уже не надо загружать сохраненные параметры. Просто смотрим энтропию, на которую надо ориентироваться
torch.manual_seed(0) # чтобы результат не менялся
for _ in seeds:    
    for alpha in sc.alpha_reduce:
        for subalpha in alpha:
            subalpha.data *= 0
            # подобрал на глаз. Вероятность первой компоненты колеблется от 0.8 до 0.98
            subalpha.data += torch.randn(subalpha.shape)
            subalpha.data[0] += 5 
    print (calc_entropy(sc, 0.2))

tensor([-2057.7263], grad_fn=<AddBackward0>)
tensor([-1738.8621], grad_fn=<AddBackward0>)
tensor([-1741.5540], grad_fn=<AddBackward0>)
tensor([-1738.5248], grad_fn=<AddBackward0>)
tensor([-1789.3007], grad_fn=<AddBackward0>)


In [15]:
# посмотрим, какова будет энтропия у моделей с единичной температурой и концентрацией плотности в центре симплекса
# здесь уже не надо загружать сохраненные параметры. Просто смотрим энтропию, на которую надо ориентироваться
torch.manual_seed(0) # чтобы результат не менялся
for _ in seeds:    
    for alpha in sc.alpha_reduce:
        for subalpha in alpha:
            subalpha.data *= 0
            # подобрал на глаз. Вероятность каждой компоненты колеблется от 0.11 о 0.17
            subalpha.data += torch.randn(subalpha.shape)*0.1
    print (calc_entropy(sc, 1))
    # NB: если делать высокую температуру, то энтропия также уменьшается:
    # сэмлпы будут концентрироваться ближе к симплексу

tensor([-117.2899], grad_fn=<AddBackward0>)
tensor([-117.5028], grad_fn=<AddBackward0>)
tensor([-115.3686], grad_fn=<AddBackward0>)
tensor([-115.5215], grad_fn=<AddBackward0>)
tensor([-118.0374], grad_fn=<AddBackward0>)


In [17]:
basecfg_path = '../configs/mnist/darts_test_igr.cfg'  #конфиг, на который мы ориентируемся при загрузки модели
cfg = ConfigObj(basecfg_path)
name = cfg['name'] # имя для сохранения результатов
ckp_path = './var_nas/searchs/'+name+'/best_{}.pth.tar' # это шаблон названия сохраненных моделей
seeds = cfg['seeds'].split(';')  # сиды. можно брать из конфига
cfg['device'] = 'cpu'
sc = SearchCNNController(**cfg)

In [58]:
#https://arxiv.org/pdf/1912.09588.pdf
def log_det_jac(logits, t):
    k = len(logits)    
    exp_logit = torch.exp(logits/t)
    eps = 0.01
    part1 = -2*(k-1) * torch.log((exp_logit.sum()))
    
    part2 = torch.log(abs(1-t*(exp_logit/(eps+logits)).sum()))
    
    part3 = -(k-1) * torch.log(t)
    
    part4 = (torch.log(abs(logits))+abs(logits/t)).sum() 
    
    return part1 + part2 + part3 +part4
log_det_jac(torch.randn(5), torch.ones(1))

tensor([-11.3271])

In [106]:
def calc_entropy(model, temp, entropy_sample_num = 100):
    entropy = 0
    for alpha, cov in zip(model.alpha_reduce, model.alpha_cov_reduce):
        for subalpha, subcov in zip(alpha, cov):
            distr = torch.distributions.lowrank_multivariate_normal.LowRankMultivariateNormal(subalpha,
                                                                                              subcov,
                                                                                              torch.ones(subalpha.shape[0]).to('cpu'))
            subentropy = 0
            for _ in range(entropy_sample_num):
                sample = distr.sample()                
                subentropy=subentropy -distr.log_prob(sample) +log_det_jac(sample, torch.ones(1)*temp)

            subentropy /= entropy_sample_num
            entropy += subentropy
    return entropy

In [107]:
# посмотрим, какова будет энтропия у моделей с низкой температурой и концентрацией плотности у одной из операций
# здесь уже не надо загружать сохраненные параметры. Просто смотрим энтропию, на которую надо ориентироваться
torch.manual_seed(0) # чтобы результат не менялся
for _ in seeds:    
    for alpha, cov in zip(sc.alpha_reduce, sc.alpha_cov_reduce):
        for subalpha, subcov in zip(alpha, cov):
            subalpha.data *= 0            
            # подобрал на глаз. Вероятность первой компоненты колеблется от 0.8 до 0.98
            subalpha.data += torch.randn(subalpha.shape)
            
            subalpha.data *= 0            
            # подобрал на глаз. Вероятность первой компоненты колеблется от 0.8 до 0.98
            subalpha.data += torch.randn(subalpha.shape)
            
            subcov.data *= 0
            subcov.data += torch.randn(subalpha.shape)*0.1
            subalpha.data[0] += 5 
    print (calc_entropy(sc, 0.2))

tensor([-2841.2993], grad_fn=<AddBackward0>)
tensor([-2933.6133], grad_fn=<AddBackward0>)
tensor([-2792.9165], grad_fn=<AddBackward0>)
tensor([-2661.6001], grad_fn=<AddBackward0>)
tensor([-2635.9458], grad_fn=<AddBackward0>)


In [108]:
# посмотрим, какова будет энтропия у моделей с единичной температурой и концентрацией плотности в центре симплекса
# здесь уже не надо загружать сохраненные параметры. Просто смотрим энтропию, на которую надо ориентироваться
torch.manual_seed(0) # чтобы результат не менялся
for _ in seeds:    
    for alpha, cov in zip(sc.alpha_reduce, sc.alpha_cov_reduce):
        for subalpha, subcov in zip(alpha, cov):
            subalpha.data *= 0
            # подобрал на глаз. Вероятность каждой компоненты колеблется от 0.11 о 0.17
            subalpha.data += torch.randn(subalpha.shape)*0.1
            
            subcov.data *= 0
            subcov.data += torch.randn(subalpha.shape)*0.1
    print (calc_entropy(sc, 1))
    # NB: если делать высокую температуру, то энтропия также уменьшается:
    # сэмлпы будут концентрироваться ближе к симплексу

tensor([-194.6946], grad_fn=<AddBackward0>)
tensor([-196.9060], grad_fn=<AddBackward0>)
tensor([-196.3895], grad_fn=<AddBackward0>)
tensor([-196.2080], grad_fn=<AddBackward0>)
tensor([-193.0515], grad_fn=<AddBackward0>)


In [ ]:
"""
Итог: для сильно фиксированных структур энтропия колеблется в районе -3000,-2500
для максимально энтропийных структур: около -200,-150
среднее значение можно брать около -1000,-700
"""